Commerce 4.4 and 4.5: Remove user_registration.group_id wrong ID
ibexa/recipes pull request #109
Opened 2023-04-28 13:47 UTC by adriendupuis

Between 4.3 and 4.4, the content tree has changed:
- In 4.3, ContentId 57 is "Private customers" user group;
- In 4.4+, ContentId 57 is "Tags" and there isn't a "Private customers" user group anymore.

The quickest fix is to just remove it to create new customers in the global default user group.

2023-04-28 13:49 UTC, ViniTou approved these changes

2023-05-08 13:52 UTC, konradoboza approved these changes

2023-05-21 13:00 UTC, adamwojs approved these changes

2023-05-22 05:57 UTC, webhdx requested changes
This PR has to be reopened against https://github.com/ibexa/recipes-dev. We don't commit to this repository directly, recipes-dev is merged to the main repository before every release..

2023-09-20 14:08 UTC, closed without merging